
spring:
  application:
    name: post-map-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.101.30:3306/post?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&userSSL=false
#    username: jyp
#    password: jyjyp123
    url: jdbc:mysql://101.133.137.140:3306/post?serverTimezone=UTC
    username: root
    password: lcl_alihost_2019070270
  thymeleaf:
    cache: false
  mail:
    username: jyp514@qq.com
    password: iurjetvskfrpbccb
    host: smtp.qq.com
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
server:
  port: 9222

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.post.db.entities

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
##      defaultZone: http://101.133.137.140:9221/eureka
      #表示是否将自己注册进EurekaServer默认为true
      register-with-eureka: true
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      fetch-registry: true
      instance:
        instance-id: map9222
#    prefer-ip-address: true #访问路径可以显示ip
##    lease-renewal-interval-in-seconds: 1
##    lease-expiration-duration-in-seconds: 2

# 配置pagehelper参数
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql