spring:
  data:
    mongodb:
      host: 106.15.170.74
      port: 27017
#      username: root
#      password: 123
      database: post
  application:
    name: post-websocket
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.101.30:3306/post?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&userSSL=false
    #    username: jyp
    #    password: jyjyp123
    url: jdbc:mysql://101.133.137.140:3306/post?serverTimezone=UTC
    username: root
    password: lcl_alihost_2019070270
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
server:
  port: 8100

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.post.db.entities

eureka:
  instance:
    instance-id: 127.0.0.1:8100
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      #      defaultZone: http://101.133.137.140:9221/eureka
      #表示是否将自己注册进EurekaServer默认为true
      register-with-eureka: true
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      fetch-registry: true