server:
  port: 9223
#  port: 9201
  ssl:
    key-store: classpath:5007830__njuptsun.xyz.pfx
#    key-password: 123456
    key-store-password: 8mNpKeDf
    key-store-type: PKCS12
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: micro-oauth2-gateway
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes: #配置路由规则
        - id: spost-api-route
          uri: lb:http://spost8001
          predicates:
            - Path=/spost/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: oauth2-auth-route
          uri: lb:http://micro-oauth2-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Vary
        - id: post-map-service
          uri: lb:http://post-map-service
          predicates:
            - Path=/post/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Vary
        - id: post-websocket
          uri: lb:ws://post-websocket
          predicates:
            - Path=/socket/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Vary
        - id: post-ctontcm-service
          uri: lb:http://post-ctontcm-service
          predicates:
            - Path=/ctontcm/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Vary
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
  #      default-filters:
  #        - PreserveHostHeader
  #        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Vary

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://101.133.137.140:9222/rsa/publicKey' #配置RSA的公钥访问地址
#          jwk-set-uri: 'http://localhost:9401/rsa/publicKey' #配置RSA的公钥访问地址

  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password:
secure:
  ignore:
    urls: #配置白名单路径
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/oauth/exit"
      - "/**/swagger-ui.html"
      - "/post/mail/**"
      - "/post/user/register"
      - "/post/mail/get"
      - "/post/map/location"
      - "/post/map/data/**"
      - "/post-websocket/**"
      - "/socket/**"
      - "/spost/photos/**"
eureka:
  instance:
    hostname: post-gateway
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://101.133.137.140:9221/eureka
#      defaultZone: http://localhost:7001/eureka
